version: "3.7"
services:
  app:
    build:
      args:
        user: paulo
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: jetstream
    container_name: jetstream-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    networks:
      - jetstream

  mysql:
    image: mysql:5.7
    container_name: jetstream-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: homestead
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 33061:3306
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - jetstream

  nginx:
    image: nginx:alpine
    container_name: jetstream-nginx
    restart: always
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - jetstream

  redis:
    image: "redis:alpine"
    container_name: jetstream-redis
    restart: unless-stopped
    ports:
      - "6381:6379"
    networks:
      - jetstream

networks:
  jetstream:
    driver: bridge
